rename i18n scope so it doesn’t collide with ‘timezone’
in order to set up a ‘package’ config for ‘timezone’
(which we do in the next commit),
we need to rename this ‘i18n!translation’ scope to something
else so the requireJS optimizer doesn’t choke like this:

Error: ENOENT: no such file or directory, open '/mnt/canvas/public/opti-
mized/translations/timezone/initialize_timezone_requireJS_plugin.js'
 In module tree:
     compiled/bundles/account_course_user_search
       jsx/account_course_user_search/store/configureStore
         jsx/account_course_user_search/reducers/rootReducer
           jsx/account_course_user_search/store/initialState
             jsx/account_course_user_search/store/tabList
               jsx/account_course_user_search/UsersPane
                 jsx/account_course_user_search/UsersList
                   jsx/account_course_user_search/UsersListRow
                     jsx/shared/EditUserDetailsDialog

Change-Id: Iebacc7d50182b48385c07f8745cee0316163f80c
Reviewed-on: https://gerrit.instructure.com/101239
Tested-by: Jenkins
Reviewed-by: Clay Diffrient <cdiffrient@instructure.com>
Product-Review: Ryan Shaw <ryan@instructure.com>
QA-Review: Ryan Shaw <ryan@instructure.com>