bumping puma version causes selenium instability; refs DE-546
comment added to warn about upgrading puma. upgrading to 2.5.2
caused "Uncaught TypeError: e.preventDefault(...) is not a function"
and "RSpec::Core::MultipleExceptionError"

Change-Id: Ie5c0b216835757604d9997cc7322dc03dbc119b0
Reviewed-on: https://gerrit.instructure.com/c/canvas-lms/+/259697
Reviewed-by: Andrea Cirulli <andrea.cirulli@instructure.com>
QA-Review: Kyle Rosenbaum <krosenbaum@instructure.com>
Product-Review: Kyle Rosenbaum <krosenbaum@instructure.com>
Tested-by: Service Cloud Jenkins <svc.cloudjenkins@instructure.com>