my kinesis won't start without this
closes RC-70

I was continuing to error with this:

kinesis_1 | LevelUPError: Failed to require LevelDOWN (Cannot find module 'leveldown/package'). Try `npm install leveldown` if it's missing

Adding the npm install command to the Dockerfile for
kinesis seemed to solve the problem.

Change-Id: I963e97761c966492fca8b3d8eec607d628902af9
Reviewed-on: https://gerrit.instructure.com/59966
Reviewed-by: Zach Wily <zach@instructure.com>
Tested-by: Jenkins
Product-Review: Ethan Vizitei <evizitei@instructure.com>
QA-Review: Ethan Vizitei <evizitei@instructure.com>