edit broken command for docker setup
The old command used to print `version: 2` instead of `version: '2'`,
which made docker-compose angry:

  ERROR: Version in "./docker-compose.local.ahuff.yml" is invalid - it should be a string.

Change-Id: Ie4d34db6f99fe3c6efc3dd439003a7a6f1a315bb
Reviewed-on: https://gerrit.instructure.com/101079
Tested-by: Jenkins
Reviewed-by: Eric Coan <ecoan@instructure.com>
Product-Review: Andrew Huff <ahuff@instructure.com>
QA-Review: Andrew Huff <ahuff@instructure.com>