Fix invalid code in select_content_dialog.js
fixes: PLAT-4914

This should have never worked, because it was trying to access a 
`const` variable before it was initialized but babel erroneously made it
work because it transpiled those `const`s down to `var`s.

Test plan:
* you should not get errors about 
  ReferenceError: Cannot access 't' before initialization
  When you run this code

Change-Id: Id669b931c985a9874b9f391971452b3c83a99f58
Reviewed-on: https://gerrit.instructure.com/209654
Tested-by: Jenkins
Reviewed-by: Marc Phillips <mphillips@instructure.com>
Reviewed-by: Xander Moffatt <xmoffatt@instructure.com>
QA-Review: Tucker Mcknight <tmcknight@instructure.com>
Product-Review: Ryan Shaw <ryan@instructure.com>